package com.example.instagramapp.base.util


object ConstValues {
    const val USER_ID = "userId"
    const val USERNAME = "username"
    const val EMAIL = "email"
    const val PASSWORD = "password"
    const val BIO = "bio"
    const val IMAGE_URL = "imageUrl"
    const val CAPTION = "caption"
    const val POST_ID = "postId"
    const val TIME = "time"
    const val POST_IMAGE_URL = "postImageUrl"
    const val COMMENT = "comment"
    const val COMMENTID = "commentId"
    const val STORY_ID = "storyId"
    const val TIME_START = "timeStart"
    const val TIME_END = "timeEnd"
    const val POSTS = "Posts"
    const val IMAGES = "images"
    const val USERS = "Users"
    const val COMMENTS = "Comments"
    const val CHATS = "Chats"
    const val SEEN = "seen"
    const val SENDER_ID = "senderId"
    const val LAST_MESSAGE = "lastmessage"
    const val MESSAGE_ID = "messageId"
    const val MESSAGE_TXT = "messagetxt"
    const val MESSAGES = "Messages"
    const val STORY_STORAGE = "story"
    const val STORY = "Story"
    const val LIKES = "Likes"
    const val FOLLOW = "Follow"
    const val FOLLOWING = "following"
    const val SAVES = "Saves"
    const val FOLLOWERS = "followers"
    const val TOKEN = "token"
}

